# Generated by Django 4.1.5 on 2023-01-17 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ferrocarril',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='manodeobra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Jefe', models.CharField(max_length=50)),
                ('emailJefe', models.EmailField(max_length=254)),
                ('Subjefe', models.CharField(max_length=50)),
                ('emailSubjefe', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='vias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
            ],
        ),
    ]
